models for repositories
DmitryV13/Planty-App pull request #1
Opened 2023-06-12 18:09 UTC by DmitryV13

я создал изначальные приблизительные сущности которые будут использоваться дальше, по возможности везде тип данных указан String, потому что сейчас создавал только структуру (потом кое что из уже существующего перейдет в тип данных для времени, также поменяться могут и типы данных других полей).

2023-06-15 09:12 UTC, AlexMurinets requested changes

2023-06-15 09:12 UTC, AlexMurinets commented on src/main/java/com/planty_app/Planty/models/Conditions.java
> +    private String temperature;//температура
не обязательно писать русский перевод для всех филдов)

2023-06-15 09:12 UTC, AlexMurinets commented on src/main/java/com/planty_app/Planty/models/Plant.java
> +    @ManyToOne()
Скобки не нужны

2023-06-15 09:12 UTC, AlexMurinets commented on src/main/java/com/planty_app/Planty/models/Watering.java
> +    private String duration;
Не думаю что String лучший вариант для хранения времени. Посмотри в сторону Instant, Local
Date

2023-06-15 09:27 UTC, DmitryV13 commented on src/main/java/com/planty_app/Planty/models/Conditions.java
> +    private String temperature;//температура
это на всякий случай для команды

2023-06-15 09:27 UTC, DmitryV13 commented on src/main/java/com/planty_app/Planty/models/Plant.java
> +    @ManyToOne()
исправлю

2023-06-15 09:39 UTC, DmitryV13 commented on src/main/java/com/planty_app/Planty/models/Watering.java
> +    private String duration;
я взял Duration и Period

2023-06-15 09:41 UTC, DmitryV13 commented on src/main/java/com/planty_app/Planty/models/Watering.java
> +    private String duration;
тогда я возьму Duration и Period

2023-06-15 13:49 UTC, AlexMurinets commented on src/main/java/com/planty_app/Planty/models/Watering.java
> +    private String amountOfWater;
Amount тоже вряд ли String

2023-06-17 07:24 UTC, AlexMurinets approved these changes

2023-06-17 12:04 UTC, merged